# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: updater.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'updater.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rupdater.proto\x12\x07updater\"\x1e\n\rUpdateRequest\x12\r\n\x05state\x18\x01 \x01(\t\" \n\x0eUpdateResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2P\n\rUpdateService\x12?\n\x0cUpdateStatus\x12\x16.updater.UpdateRequest\x1a\x17.updater.UpdateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'updater_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPDATEREQUEST']._serialized_start=26
  _globals['_UPDATEREQUEST']._serialized_end=56
  _globals['_UPDATERESPONSE']._serialized_start=58
  _globals['_UPDATERESPONSE']._serialized_end=90
  _globals['_UPDATESERVICE']._serialized_start=92
  _globals['_UPDATESERVICE']._serialized_end=172
# @@protoc_insertion_point(module_scope)
