[project]
name = "vpsij"
version = "0.1.0"
description = "Python-based job schedulers interface"
readme = "README.md"
authors = [
    { email = "soratouch@hotmail.com" }
]
requires-python = ">=3.8"
dependencies = [ 'jinja2', 'grpcio', 'grpcio-tools', 'parallel-ssh', 'urllib3' ]

[project.scripts]
vpsij-updater = "vPSIJ.job_rpc_client:main"
vpsij-setup-client = "vPSIJ.setup_client:main"

[build-system]
requires = ["uv_build>=0.6.8"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "vPSIJ"
module-root = ""